# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Git deploy to Heroku
  # You may pin to the exact commit or the version.
  # uses: onekiloparsec/heroku-node-deploy-subfolder@85d5701f800be8126e12b7f6f47e965c71f67b56
        uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
    # Your Heroku API key. This will be used for authentication. You can find it in your Heroku account settings
          api_key: 104895f0-9cf8-4386-b3d3-56295b8fc3a2
    # The email of your Heroku account (needed for auth).
          email: mtomar@student.unimelb.edu.au
    # The app name to use for deploying/updating
          app_name: vendor-app-007
    # The Heroku branch name that you would like to deploy to (`master` or `main`).
          heroku_branch: main
    # The subfolder where your built code is sitted, e.g. `dist`.
          subfolder: .
